//! Replay the Lean oracle against the mirror.
//!
//! `test_data/lean-oracle/<m>x<n>.txt` is generated by `tools/gen-oracle.sh`
//! from `lean/Oracle.lean`, which evaluates the computable twins of
//! `Defs.lean` — `resolve'`, `PlayableAt'`, `area'`, `afterC`, `step'`,
//! `start'`, `SSK'`, `PSK'` — each tied to the definition it computes by a
//! bridge lemma the Lean kernel has checked. This test asserts every row
//! against [`superko_rules::reference`] and against [`superko_rules::table`].
//!
//! # What agreement establishes
//!
//! That on the boards and rows covered, this crate computes what Lean computes
//! — `computed`, and no more. The rows themselves are graded `observed` in the
//! fixture header: the Lean *compiler* produced them, which is the trust
//! surface `native_decide` has and not the kernel's. So a green run here is
//! evidence that the mirror has not drifted, and evidence for no ledger entry.
//!
//! What it does not establish: anything about a board larger than those
//! fixtures, anything about the full game tree where the `play` traces stop at
//! their depth, and — since both sides read the same definitions — anything
//! about whether those definitions describe Go. That last is the
//! independent-agreement argument in `docs/trusted-base.md`, and it is a
//! different test.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use superko_rules::code::{encode, parse, render};
use superko_rules::config::{Dims, Point, Repetition, Suicide};
use superko_rules::reference::{
    Color, Move, Position, State, all_moves, area, ended, has_liberty, legality, permits,
    playable_at, resolve, step,
};
use superko_rules::table::RuleTable;

/// Every fixture is generated under `Defs.lean`'s own convention. `RemoveOwn`
/// has no Lean counterpart at all, so no row here could be about it.
const SUICIDE: Suicide = Suicide::Forbid;

fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../test_data/lean-oracle")
}

/// The fixtures, smallest board first, so a failure is reported on the
/// cheapest board that has it.
fn fixtures() -> Vec<(PathBuf, Dims)> {
    let dir = fixture_dir();
    let mut out: Vec<(PathBuf, Dims)> = fs::read_dir(&dir)
        .unwrap_or_else(|e| {
            panic!(
                "ORACLE-DISAGREE fixtures: cannot read {}: {e}",
                dir.display()
            )
        })
        .map(|entry| entry.expect("a directory entry").path())
        .filter(|p| p.extension().is_some_and(|e| e == "txt"))
        .map(|p| {
            let dims = dims_of(&p);
            (p, dims)
        })
        .collect();
    out.sort_by_key(|(p, dims)| (dims.point_count(), dims.rows, p.clone()));
    assert!(
        !out.is_empty(),
        "ORACLE-DISAGREE fixtures: no fixtures in {}; run tools/gen-oracle.sh",
        dir.display()
    );
    out
}

/// The board a fixture is for, read from its `# board: m n` header and checked
/// against its file name. A fixture whose name and header disagreed would be a
/// fixture read on the wrong board, and every row of it would be meaningless.
fn dims_of(path: &Path) -> Dims {
    let text = fs::read_to_string(path).expect("a fixture is readable");
    let line = text
        .lines()
        .find_map(|l| l.strip_prefix("# board: "))
        .unwrap_or_else(|| {
            panic!(
                "ORACLE-DISAGREE header: {} has no '# board:' line",
                path.display()
            )
        });
    let mut parts = line.split_whitespace();
    let rows: usize = parts.next().expect("m").parse().expect("m is a number");
    let cols: usize = parts.next().expect("n").parse().expect("n is a number");
    let name = path.file_stem().expect("a file name").to_string_lossy();
    assert_eq!(
        name,
        format!("{rows}x{cols}"),
        "ORACLE-DISAGREE header: {} is named for a different board than its header",
        path.display()
    );
    Dims::new(rows, cols)
}

fn color_of(tok: &str, ctx: &str) -> Color {
    match tok {
        "b" => Color::Black,
        "w" => Color::White,
        other => panic!("ORACLE-DISAGREE parse: {ctx}: '{other}' is not a color"),
    }
}

fn point_of(tok: &str, dims: Dims, ctx: &str) -> Point {
    let (r, c) = tok
        .split_once(',')
        .unwrap_or_else(|| panic!("ORACLE-DISAGREE parse: {ctx}: '{tok}' is not a point"));
    let p = Point::new(
        r.parse().expect("a row number"),
        c.parse().expect("a column number"),
    );
    assert!(
        dims.contains(p),
        "ORACLE-DISAGREE parse: {ctx}: {p} is off the {dims} board"
    );
    p
}

fn move_of(tok: &str, dims: Dims, ctx: &str) -> Move {
    if tok == "pass" {
        Move::Pass
    } else {
        Move::Play(point_of(tok, dims, ctx))
    }
}

fn board_of(tok: &str, dims: Dims, ctx: &str) -> Position {
    parse(dims, tok)
        .unwrap_or_else(|e| panic!("ORACLE-DISAGREE parse: {ctx}: '{tok}' is not a position: {e}"))
}

fn bit_of(tok: &str, ctx: &str) -> bool {
    match tok {
        "1" => true,
        "0" => false,
        other => panic!("ORACLE-DISAGREE parse: {ctx}: '{other}' is not 0 or 1"),
    }
}

fn rule_of(tok: &str, ctx: &str) -> Repetition {
    match tok {
        "ssk" => Repetition::Ssk,
        "psk" => Repetition::Psk,
        other => panic!("ORACLE-DISAGREE parse: {ctx}: '{other}' is not a repetition rule"),
    }
}

/// The state a `play` row's path names: fold `step` from the root of play,
/// checking at each ply that the move the path took was legal under the rule
/// and that the game had not already ended. A row whose path is not a legal
/// line is not a row about anything.
fn state_of_path(dims: Dims, path: &str, rep: Repetition, ctx: &str) -> State {
    let mut st = State::start(&Position::empty(dims), Color::Black);
    if path == "root" {
        return st;
    }
    for (i, tok) in path.split(';').enumerate() {
        let mv = move_of(tok, dims, ctx);
        assert!(
            !ended(&st),
            "ORACLE-DISAGREE trace: {ctx}: the path continues past a finished game at ply {i}"
        );
        assert!(
            permits(&st, mv, rep, SUICIDE),
            "ORACLE-DISAGREE trace: {ctx}: ply {i} ({mv}) is not legal under {rep} in the mirror"
        );
        st = step(&st, mv, SUICIDE);
    }
    st
}

/// Games from a state, counted by the plainest recursion there is: one game
/// per state where the game has ended, and otherwise the sum over the legal
/// moves. It shares no code with the Lean counter and no code with any
/// enumerator this workspace will grow.
fn count_games(st: &State, rep: Repetition) -> u64 {
    if ended(st) {
        return 1;
    }
    all_moves(st.now().board.dims())
        .into_iter()
        .filter(|&mv| permits(st, mv, rep, SUICIDE))
        .map(|mv| count_games(&step(st, mv, SUICIDE), rep))
        .sum()
}

/// A `# key: value` header line of a fixture, or `None` when it is absent.
fn header<'t>(text: &'t str, key: &str) -> Option<&'t str> {
    let prefix = format!("# {key}: ");
    text.lines().find_map(|l| l.strip_prefix(&prefix))
}

struct Seen {
    resolve: usize,
    playable: usize,
    area: usize,
    play: usize,
    count: usize,
    /// The greatest `depth` field any `play` row of the fixture carried.
    deepest_play: usize,
    /// What the fixture's `# count-table:` header promises.
    promises_count: bool,
    /// What the fixture's `# play-depth:` header promises as a ceiling.
    play_depth: usize,
}

#[allow(clippy::too_many_lines)]
fn replay(path: &Path, dims: Dims) -> Seen {
    let text = fs::read_to_string(path).expect("a fixture is readable");
    let name = path.file_name().expect("a file name").to_string_lossy();
    let table =
        RuleTable::build(dims, SUICIDE).expect("the fixture boards are within the table cap");
    let mut seen = Seen {
        resolve: 0,
        playable: 0,
        area: 0,
        play: 0,
        count: 0,
        deepest_play: 0,
        promises_count: header(&text, "count-table")
            .unwrap_or_else(|| {
                panic!("ORACLE-DISAGREE header: {name} has no '# count-table:' line")
            })
            .starts_with("yes"),
        play_depth: header(&text, "play-depth")
            .unwrap_or_else(|| panic!("ORACLE-DISAGREE header: {name} has no '# play-depth:' line"))
            .trim()
            .parse()
            .expect("a play depth is a number"),
    };

    for (lineno, line) in text.lines().enumerate() {
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        let ctx = format!("{name}:{}", lineno + 1);
        let f: Vec<&str> = line.split_whitespace().collect();
        match f[0] {
            "resolve" => {
                assert_eq!(
                    f.len(),
                    5,
                    "ORACLE-DISAGREE parse: {ctx}: resolve takes 4 fields"
                );
                let b = board_of(f[1], dims, &ctx);
                let c = color_of(f[2], &ctx);
                let p = point_of(f[3], dims, &ctx);
                let got = resolve(&b, c, p);
                assert_eq!(
                    render(&got),
                    f[4],
                    "ORACLE-DISAGREE resolve: {ctx}: Lean resolves {} {} at {p} to {}, the mirror to {}",
                    f[1],
                    f[2],
                    f[4],
                    render(&got)
                );
                assert_eq!(
                    table.succ(encode(&b), c, p),
                    encode(&got),
                    "ORACLE-DISAGREE resolve-table: {ctx}: the table disagrees with its own generator"
                );
                seen.resolve += 1;
            }
            "playable" => {
                assert_eq!(
                    f.len(),
                    6,
                    "ORACLE-DISAGREE parse: {ctx}: playable takes 5 fields"
                );
                let b = board_of(f[1], dims, &ctx);
                let c = color_of(f[2], &ctx);
                let p = point_of(f[3], dims, &ctx);
                let empty = bit_of(f[4], &ctx);
                let liberty = bit_of(f[5], &ctx);
                assert_eq!(
                    b.get(p).is_none(),
                    empty,
                    "ORACLE-DISAGREE playable-empty: {ctx}: the two disagree on whether {p} is empty"
                );
                assert_eq!(
                    has_liberty(&resolve(&b, c, p), p),
                    liberty,
                    "ORACLE-DISAGREE playable-liberty: {ctx}: the two disagree on whether the chain at {p} breathes after the play"
                );
                assert_eq!(
                    playable_at(&b, c, p, SUICIDE),
                    empty && liberty,
                    "ORACLE-DISAGREE playable: {ctx}: the mirror's conjunction is not the conjunction of Lean's two conjuncts"
                );
                assert_eq!(
                    table.playable(encode(&b), c, p),
                    empty && liberty,
                    "ORACLE-DISAGREE playable-table: {ctx}: the table disagrees with its own generator"
                );
                seen.playable += 1;
            }
            "area" => {
                assert_eq!(
                    f.len(),
                    4,
                    "ORACLE-DISAGREE parse: {ctx}: area takes 3 fields"
                );
                let b = board_of(f[1], dims, &ctx);
                let black: usize = f[2].parse().expect("a black area");
                let white: usize = f[3].parse().expect("a white area");
                assert_eq!(
                    area(&b, Color::Black),
                    black,
                    "ORACLE-DISAGREE area: {ctx}: Black's area on {}",
                    f[1]
                );
                assert_eq!(
                    area(&b, Color::White),
                    white,
                    "ORACLE-DISAGREE area: {ctx}: White's area on {}",
                    f[1]
                );
                assert_eq!(
                    (
                        table.area(encode(&b), Color::Black),
                        table.area(encode(&b), Color::White)
                    ),
                    (
                        u32::try_from(black).expect("an area fits a u32"),
                        u32::try_from(white).expect("an area fits a u32")
                    ),
                    "ORACLE-DISAGREE area-table: {ctx}: the table disagrees with its own generator"
                );
                seen.area += 1;
            }
            "play" => {
                assert_eq!(
                    f.len(),
                    10,
                    "ORACLE-DISAGREE parse: {ctx}: play takes 9 fields"
                );
                let rep = rule_of(f[1], &ctx);
                let depth: usize = f[2].parse().expect("a depth");
                let st = state_of_path(dims, f[3], rep, &ctx);
                let mv = move_of(f[6], dims, &ctx);
                let verdict = bit_of(f[7], &ctx);
                let passes: u32 = f[8].parse().expect("a pass count");
                let archive: usize = f[9].parse().expect("an archive size");

                let plies = if f[3] == "root" {
                    0
                } else {
                    f[3].split(';').count()
                };
                assert_eq!(
                    plies, depth,
                    "ORACLE-DISAGREE trace: {ctx}: the path is not {depth} plies long"
                );
                assert_eq!(
                    render(&st.now().board),
                    f[4],
                    "ORACLE-DISAGREE trace-board: {ctx}: the path leads to a different position in the mirror"
                );
                assert_eq!(
                    color_of(f[5], &ctx),
                    st.now().to_move,
                    "ORACLE-DISAGREE trace-turn: {ctx}: the two disagree on who is to move"
                );
                assert_eq!(
                    st.passes(),
                    passes,
                    "ORACLE-DISAGREE trace-passes: {ctx}: the two disagree on the pass count"
                );
                assert_eq!(
                    st.seen().len(),
                    archive,
                    "ORACLE-DISAGREE trace-archive: {ctx}: the two disagree on how many situations the archive holds"
                );
                assert_eq!(
                    permits(&st, mv, rep, SUICIDE),
                    verdict,
                    "ORACLE-DISAGREE verdict: {ctx}: Lean says {mv} is {} under {rep}, the mirror says otherwise",
                    if verdict { "legal" } else { "illegal" }
                );
                assert_eq!(
                    legality(&st, mv, rep, SUICIDE).is_ok(),
                    verdict,
                    "ORACLE-DISAGREE legality: {ctx}: the decomposed verdict is not the rule's"
                );
                seen.play += 1;
                seen.deepest_play = seen.deepest_play.max(depth);
            }
            "count" => {
                assert_eq!(
                    f.len(),
                    3,
                    "ORACLE-DISAGREE parse: {ctx}: count takes 2 fields"
                );
                let rep = rule_of(f[1], &ctx);
                let games: u64 = f[2].parse().expect("a game count");
                let st = State::start(&Position::empty(dims), Color::Black);
                assert_eq!(
                    count_games(&st, rep),
                    games,
                    "ORACLE-DISAGREE count: {ctx}: Lean counts {games} games from the empty {dims} board under {rep}"
                );
                seen.count += 1;
            }
            other => {
                panic!("ORACLE-DISAGREE parse: {ctx}: '{other}' is not a table this test knows")
            }
        }
    }
    seen
}

/// Every row of every fixture, against the reference and against the table.
#[test]
fn lean_oracle_agrees() {
    let mut totals: BTreeMap<&str, usize> = BTreeMap::new();
    for (path, dims) in fixtures() {
        let seen = replay(&path, dims);
        assert!(
            seen.resolve > 0 && seen.playable > 0 && seen.area > 0 && seen.play > 0,
            "ORACLE-DISAGREE coverage: {} is missing a table",
            path.display()
        );
        // Every position, color and point of the board, in both tables.
        let expect = 3usize.pow(u32::try_from(dims.point_count()).expect("a small board"))
            * 2
            * dims.point_count();
        assert_eq!(
            seen.resolve,
            expect,
            "ORACLE-DISAGREE coverage: {} does not cover every position, color and point",
            path.display()
        );
        assert_eq!(
            seen.playable,
            expect,
            "ORACLE-DISAGREE coverage: {} does not cover every position, color and point",
            path.display()
        );
        assert_eq!(
            seen.area,
            3usize.pow(u32::try_from(dims.point_count()).expect("a small board")),
            "ORACLE-DISAGREE coverage: {} does not carry an area row per position",
            path.display()
        );
        // A fixture's header is a promise about its rows, and a fixture that
        // lost its `count` rows would otherwise pass: the totals below are a
        // workspace-wide count, and two other boards carry `count` rows.
        assert_eq!(
            seen.count > 0,
            seen.promises_count,
            "ORACLE-DISAGREE coverage: {} carries {} count rows and its '# count-table:' header says {}",
            path.display(),
            seen.count,
            if seen.promises_count { "yes" } else { "no" }
        );
        // The header is a ceiling, not an equality: on a board where every game
        // finishes sooner the traces stop short of it, which 1x1 and 1x2 do.
        assert!(
            seen.deepest_play <= seen.play_depth,
            "ORACLE-DISAGREE coverage: {} has a play row at depth {} but its '# play-depth:' header says {}",
            path.display(),
            seen.deepest_play,
            seen.play_depth
        );
        *totals.entry("resolve").or_default() += seen.resolve;
        *totals.entry("playable").or_default() += seen.playable;
        *totals.entry("area").or_default() += seen.area;
        *totals.entry("play").or_default() += seen.play;
        *totals.entry("count").or_default() += seen.count;
    }
    assert!(
        totals["count"] > 0,
        "ORACLE-DISAGREE coverage: no fixture carries a count row"
    );
}
